type User {
    name: String!
    username: String!
}

type Session {
    token: ID!
    expiresAt: String!
}

input RegisterInput {
    name: String!
    username: String!
    password: String!
}

input LoginInput {
    username: String!
    password: String!
}

input AddEntryInput {
    date: String!
    categoryId: ID!
    sum: Int!
}

type AuthResponse {
    session: Session!
    user: User!
}

type Queries {
    ping: String
}

type Category {
    _id: ID!
    name: String!
}

type Entry {
    _id: ID!
    date: String!
    category: Category!
    sum: Int!
}

type Mutations {
    register(registerInput: RegisterInput): AuthResponse!
    login(loginInput: LoginInput): AuthResponse!
    addEntry(addEntryInput: AddEntryInput): Entry!
}

schema {
    query: Queries
    mutation: Mutations
}
